// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0LTu9ncYgAA_S0s2eteKHVwIGmbfGizI',
    appId: '1:72213017169:web:2171bfa6f0dc956dd07e70',
    messagingSenderId: '72213017169',
    projectId: 'flutter-firebase-auth-6df60',
    authDomain: 'flutter-firebase-auth-6df60.firebaseapp.com',
    storageBucket: 'flutter-firebase-auth-6df60.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jYBAYo9MRBD3PXWKSwLG94zdeGWta98',
    appId: '1:72213017169:android:65fc87e2e117639cd07e70',
    messagingSenderId: '72213017169',
    projectId: 'flutter-firebase-auth-6df60',
    storageBucket: 'flutter-firebase-auth-6df60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Nti1wnt9KHGV6F6kIFNWlSGP3SPy7Zs',
    appId: '1:72213017169:ios:fdc0d44fe709eedad07e70',
    messagingSenderId: '72213017169',
    projectId: 'flutter-firebase-auth-6df60',
    storageBucket: 'flutter-firebase-auth-6df60.appspot.com',
    iosClientId: '72213017169-18ac87fhnp0t38hj0p9b9rfu516b6dca.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4Nti1wnt9KHGV6F6kIFNWlSGP3SPy7Zs',
    appId: '1:72213017169:ios:f261ef32ea085533d07e70',
    messagingSenderId: '72213017169',
    projectId: 'flutter-firebase-auth-6df60',
    storageBucket: 'flutter-firebase-auth-6df60.appspot.com',
    iosClientId: '72213017169-r3edqc86ldk8odrih29u63herinq595e.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuth.RunnerTests',
  );
}
